### ISSUE TITLE
It's not working for me.

### ISSUE THREAD

**Issue by UglyMau** [aaronccasanova/format-grid-areas#3]
![example_grid](https://user-images.githubusercontent.com/1306965/116535781-6ecef980-a8e4-11eb-8489-c8f2d666ecd6.gif)
In this case I require the formatting by shortcut. I'm doing something wrong?
Thanks.

**Comment by acasanova-verys** [comment]
You are doing nothing wrong. Our implementation only accounts for double-quoted strings to keep the validation and formating logic simple. For example, if a user mixes and matches single and double quotes per grid row, it would introduce more complexity, and this utility is aimed to be opinionated in nature.

I discussed the issue with my co-author and our current idea is to capture the first quote (single or double) in the declaration and apply it everywhere in the formatting phase. Open to other suggestions!

Will try and get a fix in by the end of the weekend 😄

**Comment by aaronccasanova** [comment]
You are doing nothing wrong. Our implementation only accounts for double-quoted strings to keep the validation and formating logic simple. For example, if a user mixes and matches single and double quotes per grid row, it would introduce more complexity, and this utility is aimed to be opinionated in nature.

I discussed the issue with my co-author and our current idea is to capture the first quote (single or double) in the declaration and apply it everywhere in the formatting phase. Open to other suggestions!

Will try and get a fix in by the end of the weekend 😄

**Comment by UglyMau** [comment]
That was one of the first things I thought of, the quotation marks. I had also tried it with the double quotes, having had the same result I thought it was another problem.
I tried again the same code with the double quotes, see image.

Thank you!

![test2](https://user-images.githubusercontent.com/1306965/116597727-42d46800-a926-11eb-9de4-84ab284d6782.gif)

**Comment by aaronccasanova** [comment]
That is so strange! I am unable to reproduce the issue.

![2021-04-29 22 15 06](https://user-images.githubusercontent.com/32409546/116651618-71f3d500-a938-11eb-8136-b467f40b1670.gif)

I'm starting to wonder if one of the character codes in your string doesn't match our validation regex.

Would you mind opening up your devtools and pasting this snippet in the console?
(Replacing my example grid-template-areas declartion with yours)
```js
var validGridAreasRegex = /^[ ]*grid-template-areas:\s*?"(.|\n)*"\s*?;[ ]*$/i

validGridAreasRegex.test(`grid-template-areas: ". ph_opener ph_logo ph_func ."
". ph_search ph_search ph_search ."
"ph_menu ph_menu ph_menu ph_menu ph_menu"
"ph_func_menu ph_func_menu ph_func_menu ph_func_menu ph_func_menu";`)
```

**Comment by UglyMau** [comment]
I found the problem, in my case I use the Windows CRLF carriage return, with the "Linux type" LF mode it works correctly.
See below.
![example_grid](https://user-images.githubusercontent.com/1306965/116663481-74394c00-a997-11eb-8d0d-7d74aeca10f9.gif)

**Comment by aaronccasanova** [comment]
@UglyMau Thanks for reporting this issue! The extension has been updated to support CRLF characters and single-quoted declarations 👍
