### ISSUE TITLE
Add support for `grid-template` shorthand

### ISSUE THREAD

**Issue by OliverJAsh** [aaronccasanova/format-grid-areas#6]
For example:

```css
    grid-template:
      "stats . actions" auto
      "details details details" 1fr
      "description description description" auto
      / 1fr 1fr auto;
```

**Comment by aaronccasanova** [comment]
That may be a little out of scope for this tool as the `grid-template` shorthand is incredibly flexible:

![image](https://user-images.githubusercontent.com/32409546/120943523-35a85700-c6e4-11eb-8368-4de4fe46deb7.png)

My co-author and I considered adding more flexibility initially, such as support for comments, but in the end decided we would focus specifically on formatting `grid-template-areas`.

Thanks for the feature suggestion! Pull requests are welcome 🙂
